# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='xmt_design_desc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('desc_id', models.CharField(default='1', max_length=10, verbose_name='装饰物品的id')),
                ('desc_image_addr', models.CharField(default='1', max_length=200, verbose_name='装饰物品的位置')),
            ],
            options={
                'verbose_name': '装饰图片',
                'verbose_name_plural': '装饰图片',
            },
        ),
        migrations.CreateModel(
            name='xmt_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('xmt_user_id', models.CharField(default='新媒体用户id', max_length=50, verbose_name='新媒体用户ID')),
                ('user_ip', models.CharField(default='127.0.0.1', max_length=30, verbose_name='用户IP')),
                ('user_old_icon_addr', models.CharField(default='空', max_length=200, verbose_name='旧的用户头像')),
                ('user_new_icon_addr', models.CharField(default='空', max_length=200, verbose_name='新的用户头像')),
            ],
            options={
                'verbose_name': '用户id和头像',
                'verbose_name_plural': '用户id和头像',
            },
        ),
    ]
