# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmt_design_desc',
            old_name='desc_id',
            new_name='xmt_desc_id',
        ),
        migrations.RenameField(
            model_name='xmt_design_desc',
            old_name='desc_image_addr',
            new_name='xmt_desc_image_addr',
        ),
        migrations.RenameField(
            model_name='xmt_user',
            old_name='user_ip',
            new_name='xmt_user_ip',
        ),
        migrations.RenameField(
            model_name='xmt_user',
            old_name='user_new_icon_addr',
            new_name='xmt_user_new_icon_addr',
        ),
        migrations.RenameField(
            model_name='xmt_user',
            old_name='user_old_icon_addr',
            new_name='xmt_user_old_icon_addr',
        ),
    ]
