# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmt', '0002_auto_20171127_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='xmt_design_desc',
            name='xmt_desc_image',
            field=models.ImageField(default='123', upload_to='xmt/desc_image', verbose_name='装饰图片'),
        ),
    ]
