# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmt', '0003_xmt_design_desc_xmt_desc_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xmt_user',
            name='xmt_user_new_icon_addr',
            field=models.ImageField(default='xmt/user_new_icon', max_length=200, upload_to='', verbose_name='新的用户头像'),
        ),
        migrations.AlterField(
            model_name='xmt_user',
            name='xmt_user_old_icon_addr',
            field=models.ImageField(default='空', max_length=200, upload_to='xmt/user_old_icon', verbose_name='旧的用户头像'),
        ),
    ]
