# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 12:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xmt', '0004_auto_20171128_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xmt_user',
            old_name='xmt_user_new_icon_addr',
            new_name='xmt_user_new_icon',
        ),
        migrations.RenameField(
            model_name='xmt_user',
            old_name='xmt_user_old_icon_addr',
            new_name='xmt_user_old_icon',
        ),
        migrations.RemoveField(
            model_name='xmt_design_desc',
            name='xmt_desc_image_addr',
        ),
    ]
