# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmt', '0005_auto_20171128_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('real_delete', models.BooleanField(default=False)),
                ('u_num', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': '用户访问量',
                'verbose_name': '用户访问量',
            },
        ),
    ]
